# Generated by Django 5.2.1 on 2025-06-21 16:54
# backend/accounts/migrations/xxxx_populate_usernames.py
from django.db import migrations
import re

def generate_usernames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    for user in User.objects.all():
        if not user.username:
            base_username = user.email.split('@')[0]
            base_username = re.sub(r'[^a-zA-Z0-9]', '', base_username).lower()
            
            username = base_username
            counter = 1
            while User.objects.filter(username=username).exclude(pk=user.pk).exists():
                username = f"{base_username}{counter}"
                counter += 1
            
            user.username = username
            user.save()

def reverse_func(apps, schema_editor):
    pass  # Nothing to reverse

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_remove_user_business_name_and_more'),
    ]
    
    operations = [
        migrations.RunPython(generate_usernames, reverse_func),
    ]