# Generated by Django 5.2.1 on 2025-07-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_approx_latitude_property_approx_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_thumbnails/'),
        ),
    ]
