# Generated by Django 5.2.1 on 2025-07-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='privacy_radius',
            field=models.IntegerField(default=250),
        ),
    ]
