# Generated by Django 5.2.1 on 2025-05-15 20:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_schedule', models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('average', 'Average')], max_length=20, null=True)),
                ('cleanliness', models.IntegerField(blank=True, choices=[(1, 'Very Messy'), (2, 'Somewhat Messy'), (3, 'Average'), (4, 'Clean'), (5, 'Very Clean')], null=True)),
                ('noise_tolerance', models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True)),
                ('guest_policy', models.CharField(blank=True, choices=[('rarely', 'Rarely'), ('occasionally', 'Occasionally'), ('frequently', 'Frequently')], max_length=20, null=True)),
                ('study_habits', models.TextField(blank=True)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Year of study (1st, 2nd, etc.)', null=True)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('social_activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('dietary_restrictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('preferred_roommate_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('age_range_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_range_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_roommate_count', models.PositiveSmallIntegerField(default=1)),
                ('bio', models.TextField(blank=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roommate Profile',
                'verbose_name_plural': 'Roommate Profiles',
            },
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preferred_areas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roommate Request',
                'verbose_name_plural': 'Roommate Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, help_text='Percentage of compatibility', max_digits=5)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches_sent', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roommate Match',
                'verbose_name_plural': 'Roommate Matches',
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
