# Generated by Django 5.2.1 on 2025-05-31 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor_scores', models.JSONField()),
                ('user_feedback', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Great'), (5, 'Perfect')], null=True)),
                ('match_outcome', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('successful', 'Living Together'), ('unsuccessful', 'Did Not Work Out')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.roommatematch')),
            ],
            options={
                'verbose_name': 'Match Analytics',
                'verbose_name_plural': 'Match Analytics',
            },
        ),
    ]
