# Generated by Django 5.1.4 on 2025-08-23 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_pendingnotification_match_request_and_more'),
        ('roommates', '0002_matchrequest_matchrequestdailylimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchrequest',
            name='roommates_m_expires_984245_idx',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request', to='messaging.conversation'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='initial_message',
            field=models.TextField(blank=True, help_text='Optional message sent with match request', max_length=500),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='response_message',
            field=models.TextField(blank=True, help_text='Optional response message when accepting', max_length=500),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['status', 'created_at'], name='roommates_m_status_f0663b_idx'),
        ),
    ]
