# Generated by Django 5.2.1 on 2025-06-02 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_matchanalytics'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='completion_percentage',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='last_match_calculation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['university', '-created_at'], name='roommates_r_univers_04052e_idx'),
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['sleep_schedule', 'cleanliness'], name='roommates_r_sleep_s_d28b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['user', 'university'], name='roommates_r_user_id_9fe224_idx'),
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['-updated_at'], name='roommates_r_updated_e7133c_idx'),
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['completion_percentage', '-updated_at'], name='roommates_r_complet_790004_idx'),
        ),
    ]
