# Generated by Django 5.2.1 on 2025-06-11 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_roommateprofile_completion_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roommateprofile',
            name='roommates_r_univers_04052e_idx',
        ),
        migrations.RemoveIndex(
            model_name='roommateprofile',
            name='roommates_r_user_id_9fe224_idx',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='university',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='year',
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['user'], name='roommates_r_user_id_1637d3_idx'),
        ),
        migrations.AddIndex(
            model_name='roommateprofile',
            index=models.Index(fields=['-created_at'], name='roommates_r_created_fbb4b1_idx'),
        ),
    ]
