# Generated by Django 5.1.4 on 2025-08-23 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_remove_matchrequest_roommates_m_expires_984245_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, help_text='AI-calculated compatibility percentage', max_digits=5)),
                ('factor_scores', models.JSONField(default=dict, help_text='Breakdown of individual compatibility factors')),
                ('explanation', models.TextField(help_text='AI-generated explanation of why this is a good match')),
                ('key_compatibilities', models.JSONField(default=list, help_text='Top 3 reasons for compatibility')),
                ('potential_conflicts', models.JSONField(default=list, help_text='Potential areas of incompatibility')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('contacted', 'Contacted'), ('dismissed', 'Dismissed'), ('matched', 'Matched')], default='pending', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_reason', models.CharField(blank=True, max_length=100)),
                ('generation_method', models.CharField(default='algorithm_v1', help_text='Which algorithm version generated this', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this suggestion expires')),
                ('suggested_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_to_users', to='roommates.roommateprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-compatibility_score'], name='roommates_m_user_id_ce57e2_idx'), models.Index(fields=['user', '-created_at'], name='roommates_m_user_id_1c865e_idx'), models.Index(fields=['expires_at'], name='roommates_m_expires_249974_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'suggested_profile'), name='unique_pending_suggestion')],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('search', 'Search Results'), ('match', 'Match Suggestions'), ('direct', 'Direct Link'), ('conversation', 'From Conversation'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='How long the profile was viewed', null=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide viewer identity from viewed user')),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='roommates.roommateprofile')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_profile', '-viewed_at'], name='roommates_p_viewed__e18f2d_idx'), models.Index(fields=['viewer', '-viewed_at'], name='roommates_p_viewer__16c0fe_idx'), models.Index(fields=['viewed_at'], name='roommates_p_viewed__7b3980_idx'), models.Index(fields=['viewed_profile', 'viewer'], name='unique_daily_view')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment or inappropriate behavior'), ('spam', 'Spam or excessive messages'), ('fake_profile', 'Fake or misleading profile'), ('uncomfortable', 'Makes me uncomfortable'), ('other', 'Other reason')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Private notes about why this user was blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_blocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='roommates_u_blocker_14f429_idx'), models.Index(fields=['blocked', 'blocker'], name='roommates_u_blocked_a550cf_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
