# Generated by Django 5.2.1 on 2025-06-15 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0005_sync_academic_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 800x800px, Max file size: 5MB', upload_to='roommate_images/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True, help_text='Set to False if reported/under review')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roommates.roommateprofile')),
            ],
            options={
                'verbose_name': 'Roommate Profile Image',
                'verbose_name_plural': 'Roommate Profile Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate content'), ('fake', 'Fake or misleading'), ('offensive', 'Offensive content'), ('spam', 'Spam or advertisement'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='roommates.roommateprofileimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roommateprofileimage',
            index=models.Index(fields=['profile', 'is_primary'], name='roommates_r_profile_4bf01d_idx'),
        ),
        migrations.AddIndex(
            model_name='roommateprofileimage',
            index=models.Index(fields=['profile', 'order'], name='roommates_r_profile_72b192_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagereport',
            unique_together={('image', 'reported_by')},
        ),
    ]
