# Generated by Django 5.2.1 on 2025-06-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0007_roommateprofile_images_visible_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='images_visible_to',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='profile_visible_to',
        ),
    ]
