# Generated by Django 5.2.1 on 2025-06-17 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0009_roommateprofile_images_visible_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='User age', null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='budget_max',
            field=models.PositiveIntegerField(default=10000, help_text='Maximum monthly budget in MXN'),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='budget_min',
            field=models.PositiveIntegerField(default=0, help_text='Minimum monthly budget in MXN'),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_preference', 'No Preference')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('shared_room', 'Shared Room'), ('private_room', 'Private Room')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='lease_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months'), ('flexible', 'Flexible')], default='12_months', max_length=20),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='move_in_date',
            field=models.DateField(blank=True, help_text='Preferred move-in date', null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='preferred_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of preferred locations', size=None),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='work_schedule',
            field=models.TextField(blank=True, help_text='Work schedule description'),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Academic year (1-5)', null=True),
        ),
    ]
