# Generated by Django 5.2.1 on 2025-06-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0010_roommateprofile_age_roommateprofile_budget_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='age',
        ),
    ]
