# Generated by Django 5.2.1 on 2025-06-19 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0011_remove_roommateprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='contact_visible_to',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('matches_only', 'Matches Only'), ('nobody', 'Nobody')], default='matches_only', max_length=20),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='deal_breakers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Deal breakers for living together', size=None),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='personality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Personality traits', size=None),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='shared_interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Interests to share with roommates', size=None),
        ),
    ]
