# Generated by Django 5.2.1 on 2025-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0012_roommateprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
