# Generated by Django 5.2.1 on 2025-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0013_roommateprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='emergency_contact_relation',
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('guardian', 'Guardian'), ('partner', 'Partner'), ('other', 'Other')], max_length=20),
        ),
    ]
