# Generated by Django 5.2.1 on 2025-06-20 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0014_remove_roommateprofile_emergency_contact_relation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='preferred_locations',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='work_schedule',
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Has user completed initial profile setup'),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='deal_breakers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('no_smoking', 'No smoking'), ('no_pets', 'No pets'), ('same_gender_only', 'Same gender only'), ('quiet_study_required', 'Quiet study environment required'), ('no_overnight_guests', 'No overnight guests')], max_length=50), blank=True, default=list, help_text='Non-negotiable requirements', size=None),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='guest_policy',
            field=models.CharField(blank=True, choices=[('rarely', 'Rarely have guests'), ('occasionally', 'Occasionally have guests'), ('frequently', 'Frequently have guests')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='noise_tolerance',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low - Need complete silence'), (2, 'Low - Prefer quiet'), (3, 'Medium - Some noise is OK'), (4, "High - Don't mind noise"), (5, 'Very High - Love activity')], null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='sleep_schedule',
            field=models.CharField(blank=True, choices=[('early_bird', 'Early Bird (Before 10 PM)'), ('night_owl', 'Night Owl (After midnight)'), ('flexible', 'Flexible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='study_habits',
            field=models.CharField(blank=True, choices=[('quiet', 'Quiet - I need silence to study'), ('social', 'Social - I like studying with others'), ('flexible', 'Flexible - Either works for me')], max_length=20, null=True),
        ),
    ]
