# Generated by Django 5.2.1 on 2025-07-03 01:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0015_remove_roommateprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommateprofile',
            name='deal_breakers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('no_smoking', 'No smoking'), ('no_pets', 'No pets'), ('same_gender_only', 'Same gender only'), ('quiet_study_required', 'Quiet study environment required'), ('no_overnight_guests', 'No overnight guests'), ('no_late_rent', 'No late rent'), ('no_messy_common_areas', 'No messy common areas'), ('no_loud_music', 'No loud music'), ('no_different_sleep_schedules', 'No different sleep schedules'), ('cleaning_schedule_required', 'Cleaning schedule required'), ('no_substance_use', 'No substance use'), ('compatible_diets_required', 'Compatible diets required')], max_length=50), blank=True, default=list, help_text='Non-negotiable requirements', size=None),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('dorm', 'Dorm'), ('shared', 'Shared Room')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='sleep_schedule',
            field=models.CharField(blank=True, choices=[('early_bird', 'Early Bird (Before 10 PM)'), ('night_owl', 'Night Owl (After midnight)'), ('average', 'Average (10PM - Midnight)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='study_habits',
            field=models.CharField(blank=True, choices=[('at_home', 'Study at Home'), ('library', 'Library/Campus'), ('flexible', 'Flexible - Either works for me')], max_length=20, null=True),
        ),
    ]
