# Generated by Django 5.2.1 on 2025-07-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0016_alter_roommateprofile_deal_breakers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='gender',
        ),
    ]
