# Generated by Django 5.1.4 on 2025-08-23 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General'), ('property_inquiry', 'Property Inquiry'), ('sublease_inquiry', 'Sublease Inquiry'), ('application', 'Application'), ('roommate_inquiry', 'Roommate Inquiry'), ('roommate_match', 'Roommate Match')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_messages', models.BooleanField(default=True)),
                ('email_match_requests', models.BooleanField(default=True)),
                ('email_property_updates', models.BooleanField(default=True)),
                ('message_email_frequency', models.CharField(choices=[('instant', 'Instant'), ('batched', 'Every 20 minutes'), ('hourly', 'Hourly'), ('daily', 'Daily Digest'), ('never', 'Never')], default='batched', max_length=20)),
                ('owner_instant_inquiries', models.BooleanField(default=True, help_text='Property owners get instant emails for new inquiries')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', max_length=5)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('respect_quiet_hours', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('match_request', 'Match Request'), ('match_accepted', 'Match Accepted'), ('property_inquiry', 'Property Inquiry')], max_length=20)),
                ('message_preview', models.TextField(max_length=200)),
                ('message_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
