# Generated by Django 5.1.4 on 2025-08-23 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_conversation_type_and_more'),
        ('roommates', '0002_matchrequest_matchrequestdailylimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingnotification',
            name='match_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommates.matchrequest'),
        ),
        migrations.AddField(
            model_name='pendingnotification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pendingnotification',
            index=models.Index(fields=['user', 'sent', 'scheduled_for'], name='messaging_p_user_id_9ba5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingnotification',
            index=models.Index(fields=['scheduled_for', 'sent'], name='messaging_p_schedul_449765_idx'),
        ),
    ]
