# Generated by Django 5.2.1 on 2025-07-09 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversationflag_messagetemplate_and_more'),
        ('properties', '0005_alter_property_privacy_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False), ('status', 'active')), fields=('property',), name='unique_active_property_conversation'),
        ),
    ]
