# Generated by Django 5.2.1 on 2025-07-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_delivered_message_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='latest_message',
            field=models.ForeignKey(blank=True, help_text='Cache of the most recent message for performance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_latest', to='messaging.message'),
        ),
    ]
