# Generated by Django 5.2.1 on 2025-07-12 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_latest_message'),
        ('properties', '0005_alter_property_privacy_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-created_at'], name='messaging_c_status_7698c3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['property', '-updated_at'], name='messaging_c_propert_bfe013_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(condition=models.Q(('status', 'pending_response')), fields=['status'], name='pending_response_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationflag',
            index=models.Index(fields=['flagged_by', '-created_at'], name='messaging_c_flagged_75b86e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationflag',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['status'], name='pending_flags_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'read', '-created_at'], name='messaging_m_convers_617c01_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sender', 'read'], name='messaging_m_convers_8359ac_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('read', False)), fields=['read', 'delivered'], name='unread_messages_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='messaging_m_created_d51bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='messaging_m_templat_dbed70_idx'),
        ),
    ]
