# Generated by Django 5.2.1 on 2025-08-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_message_deleted_at_message_delivery_attempts_and_more'),
        ('subleases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sublease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='subleases.sublease'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General'), ('property_inquiry', 'Property Inquiry'), ('sublease_inquiry', 'Sublease Inquiry'), ('application', 'Application'), ('roommate_inquiry', 'Roommate Inquiry')], default='general', max_length=20),
        ),
    ]
